name: Deploy to Gllitch Hosting on merge

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VARS: ${{ secrets.MY_ENV_VARS }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Load Environment Variables
        run: echo "$MY_ENV_VARS" >> .env
      - name: Install Dependencies and Run Tests
        run: npm ci
      # - name: Deploy to Firebase Hosting
      #   uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: '${{ secrets.token }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FORUM_API_E4FD4 }}'
      #     channelId: live
      #     projectId: forum-api-e4fd4 
      - name: Deploy to Glitch Project
        uses: wei/git-sync@v3
        with:
          source_repo: https://${{ secrets.token }}@github.com/${{ github.repository }}.git
          source_branch: main
          destination_repo: ${{ secrets.GLITCH_GIT_URL }}
          destination_branch: master